### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by PengPeixi** [pzzhang/VinVL#13]
hello! When I extract image features with VinVL by the command :

python tools/test_sg_net.py --config-file sgg_configs/vgattr/vinvl_x152c4.yaml TEST.IMS_PER_BATCH 2 MODEL.WEIGHT models/vinvl/vinvl_vg_x152c4.pth MODEL.ROI_HEADS.NMS_FILTER 1 MODEL.ROI_HEADS.SCORE_THRESH 0.2 DATA_DIR "../maskrcnn-benchmark-1/datasets1" TEST.IGNORE_BOX_REGRESSION True MODEL.ATTRIBUTE_ON True TEST.OUTPUT_FEATURE True

I get the traceback:

Traceback (most recent call last):
  File "tools/test_sg_net.py", line 129, in <module>
    main()
  File "tools/test_sg_net.py", line 106, in main
    data_loaders_val = make_data_loader(cfg, is_train=False, is_distributed=distributed)
  File "/content/drive/MyDrive/VinVL/scene_graph_benchmark/scene_graph_benchmark/maskrcnn_benchmark/data/build.py", line 170, in make_data_loader
    datasets = build_dataset(cfg, transforms, DatasetCatalog, is_train or is_for_period)
  File "/content/drive/MyDrive/VinVL/scene_graph_benchmark/scene_graph_benchmark/maskrcnn_benchmark/data/build.py", line 45, in build_dataset
    cfg, dataset_name, factory_name, is_train
  File "/content/drive/MyDrive/VinVL/scene_graph_benchmark/scene_graph_benchmark/maskrcnn_benchmark/data/datasets/utils/config_args.py", line 7, in config_tsv_dataset_args
    assert op.isfile(full_yaml_file)
AssertionError

I guess the reason is that the file flickr30k/tsv/flickr30k.yaml is not exist, so where can I find this yaml file? Is it necessary?

I also try to delete the line : 
TEST: ("flickr30k/tsv/flickr30k.yaml",) 
in the file: vinvl_x152c4.yaml,
but after run the code, there is nothing output.

**Comment by sangwoo0123** [comment]
I'm having the same issue. Can someone please explain the cause and solution?
